services:
  - type: web
    name: cijene-me-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENV
        value: production
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_REFRESH_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: cijene-me-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: cijene-me-redis
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        value: your_cloud_name
      - key: CLOUDINARY_API_KEY
        value: your_api_key
      - key: CLOUDINARY_API_SECRET
        value: your_api_secret

  - type: redis
    name: cijene-me-redis
    ipAllowList: []
    plan: free